version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs-app-staging
    restart: unless-stopped
    ports:
      - "3000:3000"  # gd-main-app
      - "3001:3001"  # files-service
      - "3002:3002"  # notification-service
    environment:
      - NODE_ENV=production
      - FILES_PORT=3001
      - FILES_HOST=0.0.0.0
      - NOTIFICATION_PORT=3002
      - NOTIFICATION_HOST=0.0.0.0
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    command: /bin/sh -c "chmod +x /app/start-services.sh && /app/start-services.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - "incta-files-service:127.0.0.1"
      - "incta-notifications-service:127.0.0.1"

networks:
  app-network:
    driver: bridge

volumes:
  logs:
