version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP‑порт
      - "15672:15672"  # UI RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console UI
    environment:
      MINIO_ROOT_USER: devuser
      MINIO_ROOT_PASSWORD: devpassword
    volumes:
      - minio_data:/data
    networks:
      - rabbitmq_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "admin", "info", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  minio_data:

networks:
  rabbitmq_network:
