version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs-app-staging
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    depends_on:
      postgres-main:
        condition: service_started
      postgres-files:
        condition: service_started
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy g

    command: /bin/sh -c "chmod +x /app/start-services.sh && /app/start-services.sh"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - "incta-files-service:127.0.0.1"
      - "incta-notifications-service:127.0.0.1"

  postgres-main:
    image: postgres:15-alpine
    container_name: postgres-main-staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main_password
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  postgres-files:
    image: postgres:15-alpine
    container_name: postgres-files-staging
    restart: unless-stopped
    environment:
      POSTGRES_DB: files_db
      POSTGRES_USER: files_user
      POSTGRES_PASSWORD: files_password
    volumes:
      - postgres_files_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-staging
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - postgres-main
      - postgres-files

  redis:
    image: redis:7.2-alpine
    container_name: redis-staging
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes --requirepass staging_password
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "staging_password", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: mongodb-staging
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: app_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-staging
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app-network
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-staging
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP-порт
      - "15672:15672"  # UI RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network  # Было app_network, должно быть app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_main_data:
  postgres_files_data:
  pgadmin_data:
  logs:
  redis_data:
  mongo_data:
  rabbitmq_data: