apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: FILES_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: FILES_PORT
             - name: FILES_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: FILES_DATABASE_URL
             - name: S3_REGION
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: S3_REGION
             - name: S3_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: S3_URL
             - name: S3_SERVER
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: S3_SERVER
             - name: S3_ACCESS_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: S3_ACCESS_SECRET_KEY
             - name: S3_ACCESS_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: S3_ACCESS_KEY_ID
             - name: POST_FILES_BUCKET_NAME
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: POST_FILES_BUCKET_NAME
             - name: FILES_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-files-production-config-secret
                   key: FILES_HOST
