apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PRODUCTION_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PRODUCTION_URL
             - name: PG_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_HOST
             - name: MAIN_PG_DATABASE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: MAIN_PG_DATABASE
             - name: PG_USER
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_USER
             - name: PG_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_PASSWORD
             - name: PG_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_PORT
             - name: FILES_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_HOST
             - name: FILES_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_PORT
             - name: NOTIFICATION_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NOTIFICATION_HOST
             - name: NOTIFICATION_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NOTIFICATION_PORT
             - name: RABBITMQ_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RABBITMQ_HOST
             - name: RABBITMQ_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RABBITMQ_PORT
             - name: JWT_ACCESS_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_ACCESS_SECRET
             - name: JWT_ACCESS_EXPIRE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_ACCESS_EXPIRE
             - name: JWT_REFRESH_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_REFRESH_SECRET
             - name: JWT_REFRESH_EXPIRE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_REFRESH_EXPIRE
             - name: DEP_TYPE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: DEP_TYPE
             - name: RECAPTCHA_PRIVATE_KEY
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RECAPTCHA_PRIVATE_KEY
             - name: RECAPTCHA_ENABLED
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RECAPTCHA_ENABLED
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GOOGLE_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GOOGLE_CALLBACK_URL
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: GITHUB_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: GITHUB_CALLBACK_URL
             - name: FILES_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_URL
             - name: NEW_RELIC_APP_NAME
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NEW_RELIC_APP_NAME
             - name: NEW_RELIC_LICENSE_KEY
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NEW_RELIC_LICENSE_KEY
             - name: NEW_RELIC_LOG_LEVEL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NEW_RELIC_LOG_LEVEL
             - name: NEW_RELIC_ENABLED
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NEW_RELIC_ENABLED
             - name: NEW_RELIC_LOG_FORWARDING
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NEW_RELIC_LOG_FORWARDING
             - name: REDIS_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: REDIS_HOST
             - name: REDIS_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: REDIS_PORT
             - name: REDIS_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: REDIS_PASSWORD
             - name: REDIS_DB
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: REDIS_DB
             - name: FILES_ADMIN_LOGIN
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_ADMIN_LOGIN
             - name: FILES_ADMIN_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_ADMIN_PASSWORD
             - name: PAYMENTS_ADMIN_LOGIN
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PAYMENTS_ADMIN_LOGIN
             - name: PAYMENTS_ADMIN_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PAYMENTS_ADMIN_PASSWORD
             - name: PAYMENTS_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PAYMENTS_SERVICE_PORT
             - name: PAYMENTS_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PAYMENTS_SERVICE_HOST
             - name: BUSINESS_MONTHLY_PRICE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: BUSINESS_MONTHLY_PRICE
             - name: BUSINESS_THREE_MONTH_PRICE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: BUSINESS_THREE_MONTH_PRICE
             - name: BUSINESS_SIX_MONTH_PRICE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: BUSINESS_SIX_MONTH_PRICE
             - name: BUSINESS_YEARLY_PRICE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: BUSINESS_YEARLY_PRICE
             - name: PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PORT
