apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PRODUCTION_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PRODUCTION_URL
             - name: PG_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_HOST
             - name: MAIN_PG_DATABASE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: MAIN_PG_DATABASE
             - name: PG_USER
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_USER
             - name: PG_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_PASSWORD
             - name: PG_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PG_PORT
             - name: FILES_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_HOST
             - name: FILES_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: FILES_PORT
             - name: NOTIFICATION_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NOTIFICATION_HOST
             - name: NOTIFICATION_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: NOTIFICATION_PORT
             - name: RABBITMQ_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RABBITMQ_HOST
             - name: RABBITMQ_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: RABBITMQ_PORT
             - name: JWT_ACCESS_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_ACCESS_SECRET
             - name: JWT_ACCESS_EXPIRE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_ACCESS_EXPIRE
             - name: JWT_REFRESH_SECRET
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_REFRESH_SECRET
             - name: JWT_REFRESH_EXPIRE
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: JWT_REFRESH_EXPIRE
             - name: PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-main-back-production-config-secret
                   key: PORT
