apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: NOTIFICATION_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: NOTIFICATION_HOST
             - name: RABBITMQ_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: RABBITMQ_HOST
             - name: RABBITMQ_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: RABBITMQ_PORT
             - name: NOTIFICATION_EMAIL_HOST
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: NOTIFICATION_EMAIL_HOST
             - name: NOTIFICATION_SENDER_ADDRESS
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: NOTIFICATION_SENDER_ADDRESS
             - name: NOTIFICATION_SENDER_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: NOTIFICATION_SENDER_PASSWORD
             - name: PRODUCTION_URL
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: PRODUCTION_URL
             - name: NOTIFICATION_PORT
               valueFrom:
                 secretKeyRef:
                   name: incta-notifications-production-config-secret
                   key: NOTIFICATION_PORT
